package homekit

import (
	"crypto/ed25519"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/AlexxIT/go2rtc/pkg/core"
	"github.com/AlexxIT/go2rtc/pkg/hap"
	"github.com/AlexxIT/go2rtc/pkg/hap/camera"
	"github.com/AlexxIT/go2rtc/pkg/srtp"
	"github.com/pion/rtcp"
	"github.com/pion/rtp"
	psrtp "github.com/pion/srtp/v3"
)

// This accessory sends no RTP or sender report until it receives an encrypted
// receiver report, matching accessories that wait for the controller first.
type startupAccessory struct {
	t            *testing.T
	acc          *hap.Accessory
	video, audio net.PacketConn
	delay        time.Duration
	workers      sync.WaitGroup
}

func (s *startupAccessory) GetPair(string) []byte                    { return nil }
func (s *startupAccessory) AddPair(string, []byte, byte)             {}
func (s *startupAccessory) DelPair(string)                           {}
func (s *startupAccessory) GetImage(net.Conn, int, int) []byte       { return nil }
func (s *startupAccessory) GetAccessories(net.Conn) []*hap.Accessory { return []*hap.Accessory{s.acc} }
func (s *startupAccessory) GetCharacteristic(_ net.Conn, _ uint8, iid uint64) any {
	return s.acc.GetCharacterByID(iid).Value
}
func (s *startupAccessory) SetCharacteristic(_ net.Conn, _ uint8, iid uint64, value any) {
	char := s.acc.GetCharacterByID(iid)
	char.Value = value
	if char.Type != camera.TypeSetupEndpoints {
		return
	}
	var request camera.SetupEndpointsRequest
	if err := char.ReadTLV8(&request); err != nil {
		s.t.Error(err)
		return
	}
	response := camera.SetupEndpointsResponse{
		SessionID:   request.SessionID,
		Address:     camera.Address{IPAddr: "127.0.0.1", VideoRTPPort: uint16(s.video.LocalAddr().(*net.UDPAddr).Port), AudioRTPPort: uint16(s.audio.LocalAddr().(*net.UDPAddr).Port)},
		VideoCrypto: request.VideoCrypto, AudioCrypto: request.AudioCrypto,
		VideoSSRC: 1234, AudioSSRC: 5678,
	}
	if err := char.Write(&response); err != nil {
		s.t.Error(err)
		return
	}
	// Keys here are generated by this test's client, never production pairings.
	s.workers.Add(2)
	go s.releaseAfterReport(s.video, request.VideoCrypto, 1234, true)
	go s.releaseAfterReport(s.audio, request.AudioCrypto, 5678, false)
}

func (s *startupAccessory) releaseAfterReport(conn net.PacketConn, crypto camera.SRTPCryptoSuite, ssrc uint32, video bool) {
	defer s.workers.Done()
	context, err := psrtp.CreateContext([]byte(crypto.MasterKey), []byte(crypto.MasterSalt), psrtp.ProtectionProfileAes128CmHmacSha1_80)
	if err != nil {
		s.t.Error(err)
		return
	}
	conn.SetReadDeadline(time.Now().Add(2 * time.Second))
	buffer := make([]byte, 2048)
	n, remote, err := conn.ReadFrom(buffer)
	if err != nil {
		s.t.Errorf("no initial receiver report: %v", err)
		return
	}
	plain, err := context.DecryptRTCP(nil, buffer[:n], nil)
	if err != nil {
		s.t.Error(err)
		return
	}
	packets, err := rtcp.Unmarshal(plain)
	if err != nil || len(packets) != 1 {
		s.t.Errorf("invalid RTCP: %v", err)
		return
	}
	if _, ok := packets[0].(*rtcp.ReceiverReport); !ok {
		s.t.Errorf("got %T, want receiver report", packets[0])
		return
	}
	if !video {
		return
	}
	time.Sleep(s.delay)
	packet := &rtp.Packet{Header: rtp.Header{Version: 2, PayloadType: 99, SSRC: ssrc, SequenceNumber: 1, Timestamp: 90000}, Payload: []byte{0x65, 1, 2, 3}}
	plain, err = packet.Marshal()
	if err != nil {
		s.t.Error(err)
		return
	}
	encrypted, err := context.EncryptRTP(nil, plain, nil)
	if err != nil {
		s.t.Error(err)
		return
	}
	if _, err = conn.WriteTo(encrypted, remote); err != nil {
		s.t.Error(err)
	}
}

func TestStartReleasesAccessoryWaitingForReceiverReport(t *testing.T) {
	testMediaStartup(t, 0, 0, false)
}

func TestInitialMediaTimeout(t *testing.T) {
	t.Run("default deadline still expires", func(t *testing.T) {
		testMediaStartup(t, core.ConnDeadline+250*time.Millisecond, 0, true)
	})
	t.Run("caller allows later first packet", func(t *testing.T) {
		testMediaStartup(t, core.ConnDeadline+250*time.Millisecond, core.ConnDeadline+2*time.Second, false)
	})
}

func testMediaStartup(t *testing.T, delay, initialTimeout time.Duration, wantEarlyEnd bool) {
	fixture := &startupAccessory{t: t, acc: camera.NewAccessory("test", "test", "test", "test", "test"), delay: delay}
	var err error
	fixture.video, err = net.ListenPacket("udp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	defer fixture.video.Close()
	fixture.audio, err = net.ListenPacket("udp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	defer fixture.audio.Close()
	_, serverPrivate, err := ed25519.GenerateKey(nil)
	if err != nil {
		t.Fatal(err)
	}
	clientPublic, clientPrivate, err := ed25519.GenerateKey(nil)
	if err != nil {
		t.Fatal(err)
	}
	pairing := &hap.Server{DeviceID: "fixture", DevicePrivate: serverPrivate, GetClientPublic: func(string) []byte { return clientPublic }}
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, request *http.Request) {
		conn, rw, err := w.(http.Hijacker).Hijack()
		if err != nil {
			t.Error(err)
			return
		}
		defer conn.Close()
		request.Body = io.NopCloser(rw)
		_, key, err := pairing.PairVerify(request, rw)
		if err != nil {
			t.Error(err)
			return
		}
		secured, err := hap.NewConn(conn, rw, key, false)
		if err != nil {
			t.Error(err)
			return
		}
		_ = ServerHandler(fixture)(secured)
	}))
	defer server.Close()
	address := strings.TrimPrefix(server.URL, "http://")
	socket, err := net.ListenPacket("udp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	listen := socket.LocalAddr().String()
	socket.Close()
	url := fmt.Sprintf("homekit://%s?device_id=fixture&device_public=%x&client_id=test&client_private=%x", address, pairing.ServerPublic(), clientPrivate)
	client, err := Dial(url, srtp.NewServer(listen), hap.WithResolvedAddress(address))
	if err != nil {
		t.Fatal(err)
	}
	defer client.Stop()
	client.InitialTimeout = initialTimeout
	media := client.GetMedias()[0]
	track, err := client.GetTrack(media, media.Codecs[0])
	if err != nil {
		t.Fatal(err)
	}
	received := make(chan struct{}, 1)
	sender := core.NewSender(media, media.Codecs[0])
	sender.Handler = func(packet *rtp.Packet) {
		if string(packet.Payload) == string([]byte{0x65, 1, 2, 3}) {
			received <- struct{}{}
		}
	}
	sender.HandleRTP(track)
	started := time.Now()
	done := make(chan error, 1)
	defer fixture.workers.Wait()
	go func() { done <- client.Start() }()
	select {
	case <-received:
		if wantEarlyEnd {
			t.Error("default first-packet deadline did not end the session")
			return
		}
		t.Logf("authenticated startup delivered video after %s", time.Since(started))
	case err := <-done:
		if !wantEarlyEnd || err != nil {
			t.Errorf("session ended before first packet: %v", err)
		}
		client.Stop()
		return
	case <-time.After(delay + 3*time.Second):
		t.Error("accessory withheld media because the client sent no initial receiver report")
	}
	// Let the normal inactivity deadline finish before closing shared state.
	select {
	case err := <-done:
		if err != nil {
			t.Error(err)
		}
	case <-time.After(core.ConnDeadline + time.Second):
		t.Fatal("client did not finish its bounded observation")
	}
}
